{
 "title": "OpenShift  Host Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(node_boot_time_seconds, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(node_boot_time_seconds{namespace =\"$group\"}, service)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_boot_time_seconds{namespace=\"$group\",service=\"$service\"}, instance)"
    }
   },
   { "name": "aggregation", "label": "Aggregation", "query": "5s,10s,30s,1m,5m,30m,1h" },
   { "name": "port", "query": "9100" }
  ]
 },
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"} - node_boot_time_seconds{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-instance:node_cpu_seconds_total:irate5m{mode='idle',instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "RAM Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "instance:node_memory_load_bytes:total{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}"
    }
   ]
  },
  {
   "title": "SWAP Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "instance:node_swap_usage:total{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}"
    }
   ]
  },
  {
   "title": "Disk free Total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "instance:node_filesystem_free_total_bytes:sum{instance=~\"$host\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "NetStat",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
     "legendFormat": "TW"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
     "legendFormat": "Allocate"
    },
    {
     "expr": "instance:node_netstat_Tcp_PassiveOpens:irate30s{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": " instance:node_netstat_Tcp_ActiveOpens:irate30s{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "instance:node_netstat_Tcp_InSegs:irate30s{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
     "legendFormat": "InSegs"
    },
    {
     "expr": "instance:node_netstat_Tcp_OutSegs:irate30s{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
     "legendFormat": "OutSegs"
    },
    {
     "expr": " instance:node_netstat_Tcp_RetransSegs:irate30s{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
     "legendFormat": "RetransSegs"
    },
    {
     "expr": "instance:node_netstat_TcpExt_ListenDrops:irate30s{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
     "legendFormat": "ListenDrops"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "instance:node_cpu_core:count{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Basic CPU info",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"system\", instance=\"$host\"}",
       "legendFormat": "system"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"user\", instance=\"$host\"}",
       "legendFormat": "user"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"iowait\", instance=\"$host\"}",
       "legendFormat": "iowait"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"steal\", instance=\"$host\"}",
       "legendFormat": "steal"
      },
      {
       "expr": " instance:node_cpu_seconds_total:irate5m{mode=\"softirq\", instance=\"$host\"}",
       "legendFormat": "softirq"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"irq\", instance=\"$host\"}",
       "legendFormat": "irq"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"nice\", instance=\"$host\"}",
       "legendFormat": "nice"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"steal\", instance=~\"$host\"}",
       "legendFormat": "steal"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"idle\", instance=\"$host\"}",
       "legendFormat": "idle"
      }
     ]
    },
    {
     "title": "Context Switch",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "instance:node_context_switches_total:rate1m{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "Switches"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"} - node_memory_MemAvailable_bytes{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"} + node_memory_Buffers_bytes{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "Cache + Buffer"
      }
     ]
    },
    {
     "title": "Memory active/inactive (byte/sec)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "instance:node_memory_Active_bytes:rate1m{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "active "
      },
      {
       "expr": "instance:node_network_receive_bytes_total:irate1m{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "Inactive {{device}}"
      }
     ]
    },
    {
     "title": "Swap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_SwapFree_bytes{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_SwapTotal_bytes{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "Cached"
      }
     ]
    }
   ]
  },
  {
   "title": "Net",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "traff",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": " instance:node_network_receive_bytes_total:irate1m{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "recive {{device}}"
      },
      {
       "expr": "instance:node_network_transmit_bytes_total:irate1m{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "transmit  {{device}}"
      }
     ]
    },
    {
     "title": "Netstat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "CurrEstab"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "tw"
      },
      {
       "expr": "node_sockstat_sockets_used{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_sockstat_TCP_alloc{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "allocate"
      },
      {
       "expr": "instance:node_netstat_Tcp_PassiveOpens:irate30s{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "PassiveOpen"
      },
      {
       "expr": "instance:node_netstat_Tcp_ActiveOpens:irate30s{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "ActiveOpens"
      },
      {
       "expr": "instance:node_netstat_Tcp_InSegs:irate30s{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "InSegs"
      },
      {
       "expr": "instance:node_netstat_Tcp_OutSegs:irate30s{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "OutSegs"
      },
      {
       "expr": "instance:node_netstat_Tcp_RetransSegs:irate30s{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "RetransSeg"
      },
      {
       "expr": "instance:node_netstat_TcpExt_ListenDrops:irate30s{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "ListenDrop"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IOps",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": " instance:node_disk_reads_completed_total:irate1m{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": " instance:node_disk_writes_completed_total:irate1m{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": " instance:node_disk_read_bytes_total:irate1m{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "{{device}} - Successfully read bytes"
      },
      {
       "expr": "instance:node_disk_written_bytes_total:irate1m{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "{{device}} - Successfully written bytes"
      }
     ]
    },
    {
     "title": "I/O Usage Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "instance:node_disk_io_time_seconds_total:irate1m{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "{{device}} - Milliseconds spent doing I/Os"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "instance:node_filesystem_used_bytes:sum{instance=~\"$host\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "instance:node_disk_read_latensy:rate1m{ instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"} or instance:node_disk_read_latensy:irate1m{ instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "expr": "instance:node_disk_writes_latensy:rate1m{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}or instance:node_disk_writes_latensy:irate1m{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "Write {{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process and FD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process info",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "instance:node_procs_blocked:rate1md{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "Procs blocked"
      },
      {
       "expr": "instance:node_procs_running:rate1m{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "Procs running"
      }
     ]
    },
    {
     "title": "filefd_allocated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filefd_allocated{instance=~\"$host\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "filefd_allocated"
      }
     ]
    }
   ]
  }
 ]
}