{
 "title": "OpenShift HAProxy  Overview",
 "tags": [
  "haproxy",
  "Openshift"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "10s,20s,30s,40s,50s,1m" }
  ]
 },
 "panels": [
  {
   "title": "Basic Backend status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backends Up",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "haproxy:backend_up:count", "legendFormat": " {{backend}} {{instance}} " }
     ]
    },
    {
     "title": "Backends Down",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "haproxy:backend_down:count", "legendFormat": " {{backend}} {{instance}} " }
     ]
    }
   ]
  },
  {
   "title": "Basic General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total responses by HTTP code",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(code)(haproxy:frontend_http_responses_total:sum)",
       "legendFormat": "Frontend {{ code }}"
      },
      {
       "expr": "sum by(code)(haproxy:backend_http_responses_total:sum)",
       "legendFormat": "Backend {{ code }}"
      }
     ]
    },
    {
     "title": "Current total of incoming / outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (frontend) (haproxy:frontend_http_bytes_in_total:sum_irate1m)",
       "legendFormat": "IN Front {{frontend}}"
      },
      {
       "expr": "sum by (frontend) (haproxy:frontend_http_bytes_out_total:sum_irate1m)",
       "legendFormat": "OUT Front"
      },
      {
       "expr": "sum by (backend)(haproxy:backend_bytes_in_total:sum_irate1m)",
       "legendFormat": "IN Back {{backend}}"
      },
      {
       "expr": "sum by (backend)(haproxy:backend_bytes_out_total:sum_irate1m)",
       "legendFormat": "OUT Back {{backend}}"
      }
     ]
    },
    {
     "title": "Total number of connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(frontend)(haproxy:frontend_connections_total:sum_irate1m)",
       "legendFormat": "Front {{frontend}}"
      },
      {
       "expr": "sum by(backend)(haproxy:backend_connections_total:sum_irate1m)",
       "legendFormat": "Back {{backend}}"
      },
      {
       "expr": "sum(irate(haproxy_backend_connection_errors_total{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
       "legendFormat": "Back errors"
      }
     ]
    },
    {
     "title": "Total requests / responses",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": " sum by (instance) (haproxy:frontend_http_requests_total:sum_irate1m)",
       "legendFormat": "Requests {{instance}}"
      },
      {
       "expr": "sum by (backend) (haproxy:backend_response_error_total:sum_irate1m)",
       "legendFormat": "Response errors {{backend}}"
      },
      {
       "expr": "sum by (frontend) (haproxy:frontend_response_error_total:sum_irate1m)",
       "legendFormat": "Requests errors {{frontend}}"
      },
      {
       "expr": "sum by (proxy)(haproxy:backend_redispatch_warnings_total:sum_irate1m)",
       "legendFormat": "Backend redispatch {{proxy}}"
      },
      {
       "expr": "sum by (proxy)(haproxy:backend_response_retry_warnings_total:sum_irate5m)",
       "legendFormat": "Backend retry {{proxy}}"
      },
      {
       "expr": "sum by (proxy)(haproxy:frontend_http_requestst_denied_total:sum_irate1m)",
       "legendFormat": "Request denied {{proxy}"
      },
      {
       "expr": "sum by (proxy) (haproxy:backend_response_current_queue:sum)",
       "legendFormat": "Backend Queued {{{proxy}}"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (frontend)(haproxy:frontend_current_sessions:sum)",
       "legendFormat": "Frontend current sessions {{frontend}}"
      },
      {
       "expr": "sum by (frontend) (haproxy:frontend_current_session_rate:sum) ",
       "legendFormat": "Frontend current session rate {{frontend}}"
      },
      {
       "expr": "sum by (backend)(haproxy:backend_response_current_sessions:sum) ",
       "legendFormat": "Backend current sessions {{backend}}"
      },
      {
       "expr": "sum by (backend)(haproxy:backend_response_current_sessions_rate:sum) ",
       "legendFormat": "Backend current session rate {{backend}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Current total of incoming / outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (backend) (haproxy:backend_bytes_in_total:sum_irate1m) ",
       "legendFormat": "IN - {{ backend }}"
      },
      {
       "expr": "sum by (backend) (haproxy:backend_bytes_out_total:sum_irate1m) ",
       "legendFormat": "OUT - {{ backend }}"
      }
     ]
    },
    {
     "title": "Front - Current total of incoming / outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(frontend)(haproxy:frontend_http_bytes_in_total:sum_irate1m)",
       "legendFormat": "IN-{{ frontend }}"
      },
      {
       "expr": "sum by(frontend)(haproxy:frontend_http_bytes_out_total:sum_irate1m)",
       "legendFormat": "OUT-{{ frontend }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Total number of connections OK / Error",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (backend) ( haproxy:backend_connections_total:sum_irate1m) ",
       "legendFormat": "{{ backend }}"
      },
      {
       "expr": "sum by (backend) ( haproxy:backend_connections_errors_total:sum_irate1m) ",
       "legendFormat": "{{ backend }} Error"
      }
     ]
    },
    {
     "title": "Front - Total number of connections",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (frontend) (haproxy:frontend_connections_total:sum_irate1m)",
       "legendFormat": "{{ frontend }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Maximum observed number of queued requests not assigned to any server",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance) (haproxy:backend_response_max_queue:sum_irate1m)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Back - Current number of queued requests not assigned to any server",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance) (haproxy:backend_response_current_queue:sum_irate1m)",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Total of redispatch / error / retry warnings",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(proxy)(haproxy:backend_redispatch_warnings_tota:sum_irate1m)",
       "legendFormat": "Redispatch {{ proxy }}"
      },
      {
       "expr": "sum by(proxy) (haproxy:backend_response_retry_warnings_total:sum_irate5m)",
       "legendFormat": "Retry {{ proxy }}"
      },
      {
       "expr": "sum by(proxy) (haproxy:backend_response_error_total:sum_irate1m)",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Total HTTP requests OK / Error / Denied",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:frontend_http_requests_total:irate1m",
       "legendFormat": "{{ service }}"
      },
      {
       "expr": "haproxy:frontend_http_requests_errors_total:irate1m",
       "legendFormat": "{{ service }} Error"
      },
      {
       "expr": "haproxy:frontend_http_requests_denied:irate1m",
       "legendFormat": "{{ service }} Denied"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Total of HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy:backend_http_responses_total:sum)by(backend,code)",
       "legendFormat": "{{ code }} {{ backend }}"
      }
     ]
    },
    {
     "title": "Front - Total of HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(frontend,code) (haproxy_frontend_http_responses_total)",
       "legendFormat": "{{ code }} {{ frontend }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Current number of active sessions",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(backend) (haproxy:backend_response_current_sessions:sum)",
       "legendFormat": "{{ backend }}"
      }
     ]
    },
    {
     "title": "Front - Current number of active sessions",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(frontend) (haproxy:frontend_current_sessions:sum)",
       "legendFormat": "{{ frontend }}"
      }
     ]
    },
    {
     "title": "Instance - Current number of sessions rate per second over last elapsed second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:backend_response_current_sessions_rate:sum",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Front - Current number of sessions rate per second over last elapsed second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:frontend_current_session_rate:sum",
       "legendFormat": "{{ frontend }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of active sessions and limit",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:backend_max_sessions:sum",
       "legendFormat": "{{ backend }}"
      },
      {
       "expr": "haproxy:backend_limit_sessions:sum",
       "legendFormat": "{{ backend }} limit"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of active sessions and limit",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:frontend_max_sessions:sum",
       "legendFormat": " Session max {{ frontend }} "
      },
      {
       "expr": "haproxy:frontend_limit_sessions:sum",
       "legendFormat": "Session limit {{ frontend }}"
      }
     ]
    },
    {
     "title": "Back - Maximum number of sessions rate per second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy:backend_max_session_rate:sum",
       "legendFormat": "{{ backend }}"
      }
     ]
    },
    {
     "title": "Front - Maximum number of sessions rate per second and limit",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:frontend_max_session_rate:sum",
       "legendFormat": "Session max  {{frontend}}"
      },
      {
       "expr": "haproxy:frontend_limit_session_rate:sum",
       "legendFormat": " Session limit {{frontend}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Current health status of the backend",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "haproxy:backend_up:count", "legendFormat": "{{ backend }}" }
     ]
    },
    {
     "title": "Back - Total weight of the servers in the backend / Active servers backend",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "haproxy:backend_weight:sum", "legendFormat": "{{ proxy}}" }
     ]
    }
   ]
  },
  {
   "title": "By Server Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Current total of incoming / outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "haproxy:server_bytes_in_total:sum_irate1m",
       "legendFormat": "{{ server }} / IN - {{ service }}"
      },
      {
       "expr": "haproxy:server_bytes_out_total:sum_irate1m",
       "legendFormat": "{{ server }} / OUT - {{ service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Total number of connections",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy:server_connections_total:sum",
       "legendFormat": "{{ service }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Maximum observed number of queued requests assigned to this server",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "haproxy:server_max_queue:sum", "legendFormat": "{{ service }} / {{ server }}" }
     ]
    },
    {
     "title": "Server - Current number of queued requests assigned to this server",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:server_current_queue:sum_irate1m",
       "legendFormat": "{{ backend }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Total of HTTP responses OK",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:server_http_responses_total:sum_irate1m",
       "legendFormat": "{{ code }} {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Total of retry / error / redispatch warnings",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:server_retry_warnings_total:sum_irate1m",
       "legendFormat": "Retry {{ route }} {{ server }}"
      },
      {
       "expr": " haproxy:server_redispatch_warnings_total:sum_irate1m",
       "legendFormat": "Redispatch {{ route }} {{ server }}"
      },
      {
       "expr": "haproxy:server_response_errors_total:sum_irate1m",
       "legendFormat": "Error {{ route }} {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Total of HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:server_http_responses_total:sum_irate1m",
       "legendFormat": "{{ route }} {{ server }} {{ code }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Current number of active sessions",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:server_current_sessions:sum",
       "legendFormat": "{{ route }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Current number of sessions rate per second over last elapsed second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:server_current_sessions_rate:sum",
       "legendFormat": "{{ route }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Maximum observed number of sessions rate per second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:server_max_session_rate:sum",
       "legendFormat": "{{ route }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Maximum observed number of active sessions",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy:server_max_sessions:sum",
       "legendFormat": "{{ route }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Health Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Total downtime in seconds",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy:server_downtime_seconds_total:sum",
       "legendFormat": "{{ route }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Total number of failed health checks",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "haproxy:server_check_failures_total:sum",
       "legendFormat": "{{ route }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Total of connection errors",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy:server_connection_errors_total:sum_irate1m",
       "legendFormat": "{{ route }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Current weight of the server",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy:server_server_weight:sum",
       "legendFormat": "{{ server }}"
      }
     ]
    },
    {
     "title": "Server - Current health status of the server",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "haproxy:haproxy_server_up:sum", "legendFormat": "{{ route }} / {{ server }}" }
     ]
    }
   ]
  }
 ]
}