{
 "title": "Postgres Overview",
 "tags": [ "postgres" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "group",
    "query": {
     "query": "label_values(postgres_exporter_build_info,group)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(postgres_exporter_build_info{group=\"$group\"}, service)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(postgres_exporter_build_info{service=\"$service\"}, instance)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_locks_count{}, datname)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Instance info",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pg_static", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Xact commit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres:pg_stat_database_xact_commit:sumbyirate1m{datname=~\"$datname\"} or on () vector(0)"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres:pg_stat_database_tup_fetched:sum{datname=~\"$datname\"} or on () vector(0)"
    }
   ]
  },
  {
   "title": "Temp bytes counters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres:pg_stat_database_temp_bytes:sum{datname=~\"$datname\"} or on () vector(0)"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres:pg_stat_database_tup_updated:sum{datname=~\"$datname\"} or on () vector(0)"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{} - node_boot_time_seconds{}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-instance:node_cpu_seconds_total:irate5m{mode=\"idle\",}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "RAM Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " instance:node_memory_load_bytes:total{}"
    }
   ]
  },
  {
   "title": "Xact rollback",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres:pg_stat_database_xact_rollback:sumbyirate1m{datname=~\"$datname\"} or on () vector(0)"
    }
   ]
  },
  {
   "title": "Temp file counters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres:pg_stat_database_temp_files:sum{datname=~\"$datname\"} or on () vector(0)"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres:pg_stat_database_tup_inserted:sum{datname=~\"$datname\"} or on () vector(0)"
    }
   ]
  },
  {
   "title": "Statements max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_pg_stat_statements_max{}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "instance:node_cpu_core:count{}" }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum( node_memory_MemTotal_bytes{})"
    }
   ]
  },
  {
   "title": "Basic CPU info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"system\"}",
     "legendFormat": "system"
    },
    {
     "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"user\"}",
     "legendFormat": "user"
    },
    {
     "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"iowait\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"steal\"}",
     "legendFormat": "steal"
    },
    {
     "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"softirq\"}",
     "legendFormat": "softirq"
    },
    {
     "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"irq\"}",
     "legendFormat": "irq"
    },
    {
     "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"nice\"}",
     "legendFormat": "nice"
    },
    {
     "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"nice\"}",
     "legendFormat": "steal"
    },
    {
     "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"idle\"}",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Top request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 20 Most long request time to database",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_mean_exec_time:topk20_increase10m{}"
      }
     ]
    },
    {
     "title": "Top 20 Most called request to database",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_calls:topk20_increase10m{datname=~\"$datname\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active sessions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", state=\"active\"} !=0 ",
       "legendFormat": "{{instance}},{{datname}},state : {{state}}"
      }
     ]
    },
    {
     "title": "Idle sessions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
       "legendFormat": "{{instance}},{{datname}},state : {{state}}"
      }
     ]
    },
    {
     "title": "Numbackends",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_numbackends{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lock tables",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_locks_count{datname=~\"$datname\"} != 0",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_database_deadlocks:rate1m{datname=~\"$datname\"} or on () vector(0)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Max TX duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "pg_stat_activity_max_tx_duration{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Conflicts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_database_conflicts_confl_deadlock:rate1m{datname=~\"$datname\"}",
       "legendFormat": "{{datname}} deadlock"
      },
      {
       "expr": "postgres:pg_stat_database_conflicts:rate1m{datname=~\"$datname\"}or on () vector(0) ",
       "legendFormat": "{{datname}} conflicts"
      },
      {
       "expr": "postgres:pg_stat_database_conflicts_confl_bufferpin:rate1m{datname=~\"$datname\"}or on () vector(0)",
       "legendFormat": "{{datname}} bufferpin"
      },
      {
       "expr": "postgres:pg_stat_database_conflicts_confl_snapshot:rate1m{datname=~\"$datname\"} or on () vector(0)",
       "legendFormat": "{{datname}} shaphot"
      },
      {
       "expr": "postgres:pg_stat_database_conflicts_confl_tablespace:rate1m{datname=~\"$datname\"} or on () vector(0)",
       "legendFormat": "{{datname}} tablespace"
      }
     ]
    }
   ]
  },
  {
   "title": "Planning the statements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total rows retrieved or affected by the statement",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_rows:sum_increase1m{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total time spent planning the statement",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_total_exec_time:sum_rate1m{}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Maximum time spent planning the statement",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_max_exec_time:sum_rate1m{}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Mean time spent planning the statement",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_mean_exec_time:sum_rate1m{}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Deviation of time spent executing the statement, in millisecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_stddev_exec_time:sum_rate1m{}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Minimum time spent planning the statement",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_min_plan_time:sum_rate1m{}",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch data (SELECT)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\"} != 0",
       "legendFormat": "{{instance}}, {{datname}}"
      }
     ]
    },
    {
     "title": "Insert data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\"} != 0",
       "legendFormat": "{{instance}}, {{datname}}"
      }
     ]
    },
    {
     "title": "Update data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_updated{datname=~\"$datname\"} != 0",
       "legendFormat": "{{instance}}, {{datname}}"
      }
     ]
    },
    {
     "title": "Delete data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\"} != 0",
       "legendFormat": "{{instance}}, {{datname}}"
      }
     ]
    },
    {
     "title": "Return data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_returned{datname=~\"$datname\"} != 0",
       "legendFormat": "{{instance}}, {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statements block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of shared block cache hits by the statement",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_shared_blks_hit:sum_increase1m{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of shared blocks read by the statement",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_shared_blks_read:sum_increase1m{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of shared blocks dirtied by the statement",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_shared_blks_read:sum_increase1m{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of local block cache hits by the statement",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_local_blks_hit:sum_increase1m{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of local blocks read by the statement",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_local_blks_read:sum_increase1m{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total time the statement spent writing blocks, in milliseconds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_blk_write_time:sum_increase1m{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of temp blocks written by the statement",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_temp_blks_written:sum_increase1m{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of temp blocks read by the statement",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_temp_blks_read:sum_increase1m{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of shared blocks dirtied by the statement",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_shared_blks_dirtied:sum_increase1m{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of local blocks dirtied by the statement",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_local_blks_dirtied:sum_increase1m{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of temp blocks written by the statement",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_statements_temp_blks_written:sum_increase1m{datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blk hits/read",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_database_blks_hit:sumbyrate1{datname=~\"$datname\"}or on () vector(0)",
       "legendFormat": "Hits"
      },
      {
       "expr": "postgres:pg_stat_database_blks_read:sumbyrate1{datname=~\"$datname\"}or on () vector(0)",
       "legendFormat": "Reads"
      }
     ]
    },
    {
     "title": "Blk read/whrite time - rate 1m",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "postgres:pg_stat_database_blk_read_time:rate1m{datname=~\"$datname\"}or on () vector(0)",
       "legendFormat": "{{datname}}"
      },
      {
       "expr": "postgres:pg_stat_database_blk_write_time:rate1m{datname=~\"$datname\"}or on () vector(0)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": " instance:node_disk_reads_completed_total:irate1m{}",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": " instance:node_disk_writes_completed_total:irate1m{}",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "Disk Use",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "instance:node_filesystem_used_bytes:sum{}",
       "legendFormat": "{{instance}} , {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "instance:node_disk_read_latensy:rate1m{} or instance:node_disk_read_latensy:irate1m{}",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "expr": "instance:node_disk_writes_latensy:rate1m{}or instance:node_disk_writes_latensy:irate1m{}",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    }
   ]
  }
 ]
}